#pragma once

#ifndef EIGHT_MINUTE_EMPIRE_AFTERACTIONDRIVER_H
#define EIGHT_MINUTE_EMPIRE_AFTERACTIONDRIVER_H

#include "Cards.h"

void afterActionExample();


#endif //EIGHT_MINUTE_EMPIRE_AFTERACTIONDRIVER_H
